export const RESET_STATE = 'RESET_STATE';

export const TRANSLATE_CHANGE = 'TRANSLATE_CHANGE';
export const TRANSLATE_LOADER = 'TRANSLATE_LOADER';

export const MOBILE_DETECT_CHANGE = 'MOBILE_DETECT_CHANGE';

export const LOGIN_FORM_LOADER = 'LOGIN_FORM_LOADER';
export const LOGIN_FORM_SUCCESS = 'LOGIN_FORM_SUCCESS';
export const LOGIN_FORM_FAIL = 'LOGIN_FORM_FAIL';

export const REGISTER_FORM_LOADER = 'REGISTER_FORM_LOADER';
export const REGISTER_FORM_SUCCESS = 'REGISTER_FORM_SUCCESS';
export const REGISTER_FORM_FAIL = 'REGISTER_FORM_FAIL';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const RESTORE_PASSWORD_SEND_CODE_EMAIL = 'RESTORE_PASSWORD_SEND_CODE_EMAIL';
export const RESTORE_PASSWORD_SEND_CODE_SUCCESS = 'RESTORE_PASSWORD_SEND_CODE_SUCCESS';
export const RESTORE_PASSWORD_SEND_CODE_FAIL = 'RESTORE_PASSWORD_SEND_CODE_FAIL';
export const RESTORE_PASSWORD_CHANGE_EMAIL = 'RESTORE_PASSWORD_CHANGE_EMAIL';
export const RESTORE_PASSWORD_VERIFY_EMAIL = 'RESTORE_PASSWORD_VERIFY_EMAIL';
export const RESTORE_PASSWORD_VERIFY_SUCCESS = 'RESTORE_PASSWORD_VERIFY_SUCCESS';
export const RESTORE_PASSWORD_VERIFY_FAIL = 'RESTORE_PASSWORD_VERIFY_FAIL';

export const VERIFY_EMAIL_LOADER = 'VERIFY_EMAIL_LOADER';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL';

export const PROFILE_DETAIL_PAGE_INIT = 'PROFILE_DETAIL_PAGE_INIT';
export const PROFILE_DETAIL_PAGE_FAIL = 'PROFILE_DETAIL_PAGE_FAIL';
export const PROFILE_DETAIL_PAGE_CHANGE_DATA = 'PROFILE_DETAIL_PAGE_CHANGE_DATA';

export const PROFILE_DETAIL_FORM_LOADER = 'PROFILE_DETAIL_FORM_LOADER';
export const PROFILE_DETAIL_FORM_SUCCESS = 'PROFILE_DETAIL_FORM_SUCCESS';
export const PROFILE_DETAIL_FORM_FAIL = 'PROFILE_DETAIL_FORM_FAIL';

export const PROFILE_GALLERY_UPLOAD_LOADER = 'PROFILE_GALLERY_UPLOAD_LOADER';
export const PROFILE_GALLERY_UPLOAD_SUCCESS = 'PROFILE_GALLERY_UPLOAD_SUCCESS';
export const PROFILE_GALLERY_UPLOAD_FAIL = 'PROFILE_GALLERY_UPLOAD_FAIL';

export const PROFILE_GALLERY_LIST_COMPLETE = 'PROFILE_GALLERY_LIST_COMPLETE';
export const PROFILE_GALLERY_LIST_ERROR_INIT = 'PROFILE_GALLERY_LIST_ERROR_INIT';
export const PROFILE_GALLERY_LIST_APPEND_LOADER = 'PROFILE_GALLERY_LIST_APPEND_LOADER';
export const PROFILE_GALLERY_LIST_ADD_MODELS = 'PROFILE_GALLERY_LIST_ADD_MODELS';

export const PROFILE_GALLERY_ITEM_INIT = 'PROFILE_GALLERY_ITEM_INIT';
export const PROFILE_GALLERY_ITEM_IS_LOADED = 'PROFILE_GALLERY_ITEM_IS_LOADED';
export const PROFILE_GALLERY_ITEM_SAVE = 'PROFILE_GALLERY_ITEM_SAVE';
export const PROFILE_GALLERY_ITEM_SAVE_OK = 'PROFILE_GALLERY_ITEM_SAVE_OK';
export const PROFILE_GALLERY_ITEM_SAVE_FAIL = 'PROFILE_GALLERY_ITEM_SAVE_FAIL';
export const PROFILE_GALLERY_ITEM_DELETE = 'PROFILE_GALLERY_ITEM_DELETE';

export const PROFILE_LOCATION_FETCH_COMPLETED = 'PROFILE_LOCATION_FETCH_COMPLETED';
export const PROFILE_LOCATION_UPDATE = 'PROFILE_LOCATION_UPDATE';
export const PROFILE_LOCATION_UPDATED = 'PROFILE_LOCATION_UPDATED';

export const PROFILE_GAMES_FETCHED = 'PROFILE_GAMES_FETCHED';
export const PROFILE_GAMES_CHANGE_VALUES = 'PROFILE_GAMES_CHANGE_VALUES';
export const PROFILE_GAMES_UPDATE = 'PROFILE_GAMES_UPDATE';
export const PROFILE_GAMES_UPDATE_SUCCESS = 'PROFILE_GAMES_UPDATE_SUCCESS';
export const PROFILE_GAMES_UPDATE_FAIL = 'PROFILE_GAMES_UPDATE_FAIL';

export const PEOPLE_LIST_LOADER_LIST = 'PEOPLE_LIST_LOADER_LIST';
export const PEOPLE_LIST_QUERY = 'PEOPLE_LIST_QUERY';
export const PEOPLE_LIST_ERROR = 'PEOPLE_LIST_ERROR';

export const GALLERY_LIST_USER_LOADER = 'GALLERY_LIST_USER_LOADER';
export const GALLERY_LIST_USER_QUERY = 'GALLERY_LIST_USER_QUERY';
export const GALLERY_LIST_USER_ERROR = 'GALLERY_LIST_USER_ERROR';
export const GALLERY_LIST_USER_CLEAR = 'GALLERY_LIST_USER_CLEAR';

export const LOADER_ON = 'LOADER_ON';
export const LOADER_OFF = 'LOADER_OFF';

export const USER_DETAIL_FETCH = 'USER_DETAIL_FETCH';
export const USER_DETAIL_CLEAR = 'USER_DETAIL_CLEAR';
export const USER_DETAIL_ERROR = 'USER_DETAIL_ERROR';

export const NEW_FRIEND_REQUEST_RESULT = 'NEW_FRIEND_REQUEST_RESULT';
export const NEW_FRIEND_REQUEST_CHANGE = 'NEW_FRIEND_REQUEST_CHANGE';

export const INVITE_FORM_SENDING = 'INVITE_FORM_SENDING';
export const INVITE_FORM_ERROR = 'INVITE_FORM_ERROR';
export const INVITE_FORM_SUCCESS = 'INVITE_FORM_SUCCESS';
export const INVITE_FORM_CLEAR = 'INVITE_FORM_CLEAR';

export const INVITE_LIST_LOADER_LIST = 'INVITE_LIST_LOADER_LIST';
export const INVITE_LIST_QUERY = 'INVITE_LIST_QUERY';
export const INVITE_LIST_ERROR = 'INVITE_LIST_ERROR';
export const INVITE_LIST_TRANSFORM = 'INVITE_LIST_TRANSFORM';

export const NOTIFY_CHANGE = 'NOTIFY_CHANGE';

export const INVITE_CONTROL_LOADER = 'INVITE_CONTROL_LOADER';
export const INVITE_CONTROL_SUCCESS = 'INVITE_CONTROL_SUCCESS';
export const INVITE_CONTROL_ERROR = 'INVITE_CONTROL_ERROR';

export const CHAT_CHOOSE_CHAT = 'CHAT_CHOOSE_CHAT';
export const CHAT_BACK_TO_LIST = 'CHAT_BACK_TO_LIST';
export const CHAT_VOLUME_ON = 'CHAT_VOLUME_ON';
export const CHAT_VOLUME_OFF = 'CHAT_VOLUME_OFF';
export const CHAT_TOGGLE = 'CHAT_TOGGLE';

export const CHAT_LIST_USER_LOADER = 'CHAT_LIST_USER_LOADER';
export const CHAT_LIST_USER_QUERY = 'CHAT_LIST_USER_QUERY';
export const CHAT_LIST_USER_ERROR = 'CHAT_LIST_USER_ERROR';

export const MESSAGE_LIST_USER_LOADER = 'MESSAGE_LIST_USER_LOADER';
export const MESSAGE_LIST_USER_QUERY = 'MESSAGE_LIST_USER_QUERY';
export const MESSAGE_LIST_USER_ERROR = 'MESSAGE_LIST_USER_ERROR';
export const MESSAGE_LIST_USER_ADD_ITEM = 'MESSAGE_LIST_USER_ADD_ITEM';
export const MESSAGE_LIST_USER_CLEAR = 'MESSAGE_LIST_USER_CLEAR';

export const CHAT_MESSAGE_FORM_SUBMIT = 'CHAT_MESSAGE_FORM_SUBMIT';
export const CHAT_MESSAGE_FORM_COMPLETE = 'CHAT_MESSAGE_FORM_COMPLETE';
export const CHAT_MESSAGE_FORM_CLEAR = 'CHAT_MESSAGE_FORM_CLEAR';

export const CHAT_NEW_MESSAGES_FETCH = 'CHAT_NEW_MESSAGES_FETCH';

export const ONLINE_USERS_UPDATE = 'ONLINE_USERS_UPDATE';
export const ONLINE_USERS_LIVE = 'ONLINE_USERS_LIVE';